
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  WORKING_DIRECTORY: front-end

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - run: echo "Your repository is ${{ github.repository }}."
      - run: ls ${{ github.workspace }}

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          
      - run: echo "Your repository is ${{ github.repository }}."
      - run: ls ${{ github.workspace }}
      
      - name: npm ci
        run: npm ci
        working-directory: ${{env.WORKING_DIRECTORY}}
      
      - run: echo "Your repository is ${{ github.repository }}."
      - run: ls ${{ github.workspace }}
      
      - name: npm test
        run: npm test
        working-directory: ${{env.WORKING_DIRECTORY}}
        
      - name: npm build
        run: npm build --if-present
          
          
      # Runs the Sonar Cloud Testing
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
