apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-tothemoon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-tothemoon
  template:
    metadata:
      labels:
        app: frontend-tothemoon
    spec:
      containers:
      - name: frontend-tothemoon
        image: yellenick/frontend-tothemoon:${{gihub.run_number}}
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-tothemoon
spec:
  ports:
  - port: 80
  selector:
    app: frontend-tothemoon
